class Author < ApplicationRecord
  # Attributes from database
  attr_accessor id: Integer?
  attr_accessor name: String?
  attr_accessor created_at: Time?
  attr_accessor updated_at: Time?

  # Associations
  def books: () -> ActiveRecord::Associations::CollectionProxy
  def books=: (Array[Book]) -> Array[Book]
end
